# config.py
"""
Single source of truth for all static configuration data.
Includes the COMPLETE alarm code mapping from the specification document.
"""

CEID_MAP = {
    # GEM Events
    7: "GemOpCommand", 11: "Equipment Offline", 12: "Control State Local", 13: "Control State Remote",
    14: "GemMsgRecognition", 16: "PP-SELECT Changed", 30: "Process State Change",
    101: "Alarm Cleared", 102: "Alarm Set",

    # Custom/Alarm related CEIDs found in logs
    18: "AlarmSet", 113: "AlarmSet", 114: "AlarmSet",

    # Equipment Inherent Events
    120: "IDRead", 121: "UnloadedFromMag", 122: "LoadedToMag", 126: "UnloadedFromTool",
    127: "LoadedToTool", 128: "PP-Selected", 131: "LoadToToolCompleted", 132: "UnloadFromToolCompleted",
    133: "MagToMagCompleted", 134: "MagCheckedCompleted", 136: "MappingCompleted",
    141: "PortStatusChange", 151: "MagazineDocked", 180: "RequestMagazineDock",
    181: "MagazineDocked", 182: "MagazineUndocked", 183: "RequestOperatorIdCheck",
    184: "RequestOperatorLogin", 185: "RequestMappingCheck",
}

RPTID_MAP = {
    8: ['OperatorCommand'], 11: ['ControlState'], 14: ['Clock'], 16: ['PPChangeName', 'PPChangeStatus'],
    32: ['ProcessState', 'PreviousProcessState'], 101:['Clock', 'AlarmID'],
    120: ['LotID', 'PanelID', 'Orientation', 'ResultCode', 'SlotID'],
    121: ['LotID', 'PanelID', 'SourcePortID'], 141: ['PortID', 'PortStatus'],
    150: ['MagazineID'], 151: ['PortID', 'MagazineID', 'OperatorID'], 152: ['OperatorID'],
}

# --- COMPLETE ALARM DATABASE ---
ALARM_DB = {
    1: {'description': '<0001>CPU error', 'level': 'Error'}, 2: {'description': '<0002>SafetyPLC error', 'level': 'Error'},
    9: {'description': '<0051>EtherNet/IP error', 'level': 'Error'}, 10: {'description': '<0052>Profinet Communication Error', 'level': 'Error'},
    14: {'description': '<0056>Type setting error', 'level': 'Error'}, 15: {'description': '<0057>LP Layout setting not selected', 'level': 'Error'},
    17: {'description': '<0190>Emergency stop', 'level': 'Error'}, 18: {'description': '<0191>Safety door open', 'level': 'Error'},
    19: {'description': '<0192>Emergency stop(Option)', 'level': 'Error'}, 20: {'description': '<0193>Safety door open(Option)', 'level': 'Error'},
    21: {'description': '<0194>External EMO', 'level': 'Error'}, 65: {'description': '<0AE0>FAN warning', 'level': 'Warning'},
    66: {'description': '<0AE1>Production Interruped warning', 'level': 'Warning'}, 67: {'description': '<0AE2>Abnormaly-CommandEnd warning', 'level': 'Warning'},
    69: {'description': '<0AE4>Failed_CollectOperationRecord_HC', 'level': 'Warning'}, 70: {'description': '<0AE5>BFLMode-MES NoResponce', 'level': 'Warning'},
    71: {'description': '<0AE6>FFU1 warning', 'level': 'Warning'}, 72: {'description': '<0AE7>FFU2 warning', 'level': 'Warning'},
    73: {'description': '<0AE8>FFU3 warning', 'level': 'Warning'}, 74: {'description': '<0AE9>SYS_MCP_FAN1 Warning', 'level': 'Warning'},
    75: {'description': '<0AEA>SYS_MCP_FAN2 Warning', 'level': 'Warning'}, 76: {'description': '<0AEB>SYS_DC FAN1 Warning', 'level': 'Warning'},
    77: {'description': '<0AEC>SYS_DC FAN2 Warning', 'level': 'Warning'}, 78: {'description': '<0AED>SYS_DC FAN3 Warning', 'level': 'Warning'},
    79: {'description': '<0AEE>SYS_DC FAN4 Warning', 'level': 'Warning'}, 81: {'description': '<0AF0>VRS-Mode Waiting for SMEMA signal', 'level': 'Warning'},
    82: {'description': '<0AF1>VRS-ModeAbnormal Complete', 'level': 'Warning'}, 83: {'description': '<0AF2>Waiting the panel from VRS side', 'level': 'Warning'},
    84: {'description': '<0AF3>Vision not online', 'level': 'Warning'}, 97: {'description': '<1050>Panel fall out', 'level': 'Error'},
    98: {'description': '<1051>Interference error', 'level': 'Error'}, 99: {'description': '<1052>Conveyor driver error', 'level': 'Error'},
    100: {'description': '<1053>HNC not online', 'level': 'Error'}, 101: {'description': '<1054>Vision not online', 'level': 'Error'},
    102: {'description': '<1055>Homing impossible(W-Axis)', 'level': 'Error'}, 103: {'description': '<1056>CV driver Com. error', 'level': 'Error'},
    113: {'description': '<10F0>HNC error', 'level': 'Error'}, 114: {'description': '<10F1>Fork Coll.Detect error', 'level': 'Error'},
    129: {'description': '<1550>Panel existAlarm', 'level': 'Alarm'}, 131: {'description': '<1552>Panel pick NG', 'level': 'Alarm'},
    132: {'description': '<1553>Fork positionAlarm', 'level': 'Alarm'}, 133: {'description': '<1554>Order slot panel not exist', 'level': 'Alarm'},
    134: {'description': '<1555>Desitination slot panel exist', 'level': 'Alarm'}, 135: {'description': '<1556>SMEMA interface stop', 'level': 'Alarm'},
    136: {'description': '<1557>Panel positionAbnormally', 'level': 'Alarm'}, 137: {'description': '<1558>Motion time over [Pick]', 'level': 'Alarm'},
    138: {'description': '<1559>Motion time over [Place]', 'level': 'Alarm'}, 139: {'description': '<155A>Motion time over [Carry-in]', 'level': 'Alarm'},
    140: {'description': '<155B>Motion time over [Carry-out]', 'level': 'Alarm'}, 141: {'description': '<155C>Motion time over [Mapping]', 'level': 'Alarm'},
    142: {'description': '<155D>Motion time over [IDRead]', 'level': 'Alarm'}, 143: {'description': '<155E>Motion time over [Home]', 'level': 'Alarm'},
    144: {'description': '<155F>Panel separationAlarm', 'level': 'Alarm'}, 145: {'description': '<15A0>Process-Panel removed', 'level': 'Alarm'},
    146: {'description': '<15A1>Process-Panel existAlarm', 'level': 'Alarm'}, 147: {'description': '<15A2>Process-SMEMA signalAlarm', 'level': 'Alarm'},
    169: {'description': '<1A08>Direction wait time over', 'level': 'Warning'}, 170: {'description': '<1A09>Magazine full warning', 'level': 'Warning'},
    171: {'description': '<1A0A>Mapping data mismatch', 'level': 'Warning'}, 172: {'description': '<1A0B>ReplyMappingCheck Failed for MES', 'level': 'Warning'},
    193: {'description': '<20A0>Port1-MagLift Inverter error', 'level': 'Error'}, 194: {'description': '<20A1>Port1-Shutter Inverter error', 'level': 'Error'},
    195: {'description': '<20A2>Port1-CSLD Inverter error', 'level': 'Error'}, 196: {'description': '<20A3>Port1-MSLD Driver error', 'level': 'Error'},
    197: {'description': '<20A4>Port1-MPOS Driver error', 'level': 'Error'}, 198: {'description': '<20A5>Port1-CLOC Driver error', 'level': 'Error'},
    199: {'description': '<20A6>Port1-Homing Impossible', 'level': 'Error'}, 201: {'description': '<20A8>Port1-MagLift Com. error', 'level': 'Error'},
    202: {'description': '<20A9>Port1-Shutter Com. error', 'level': 'Error'}, 203: {'description': '<20AA>Port1-CSLD Com. error', 'level': 'Error'},
    204: {'description': '<20AB>Port1-MSLD Com. error', 'level': 'Error'}, 205: {'description': '<20AC>Port1-MPOS Com. error', 'level': 'Error'},
    206: {'description': '<20AD>Port1-CLOC Com. error', 'level': 'Error'}, 209: {'description': '<20F0> Port1-CLOC Motion error', 'level': 'Error'},
    210: {'description': '<20F1> Port1-CLOC Memory Lost error', 'level': 'Error'}, 249: {'description': '<2558>Port1-Shutter interlock', 'level': 'Alarm'},
    250: {'description': '<2559>Port1-Shutter interlock', 'level': 'Alarm'}, 251: {'description': '<255A>Port1-Panel positionAbnormally', 'level': 'Alarm'},
    252: {'description': '<255B>Port1-RFID read error [Read NG]', 'level': 'Alarm'}, 253: {'description': '<255C>Port1-MSLD interlock', 'level': 'Alarm'},
    254: {'description': '<255D>Port1-MPOS interlock', 'level': 'Alarm'}, 255: {'description': '<255E>Port1-CLOC interlock', 'level': 'Alarm'},
    256: {'description': '<255F>Port1-CSLD interlock', 'level': 'Alarm'}, 257: {'description': '<2A00>Port1-Shutter open warning', 'level': 'Warning'},
    258: {'description': '<2A01>Port1-Shutter close warning', 'level': 'Warning'}, 260: {'description': '<2A03>Port1-Mag.Lift up warning', 'level': 'Warning'},
    261: {'description': '<2A04>Port1-Mag.Lift down warning', 'level': 'Warning'}, 262: {'description': '<2A05>Port1-Mappingtimeout warning', 'level': 'Warning'},
    263: {'description': '<2A06>Port1-MappingMismatch warning', 'level': 'Warning'}, 264: {'description': '<2A07>Port1_SafetySensor warning', 'level': 'Warning'},
    265: {'description': '<2A08>Port1-MSLD_BWD timeout', 'level': 'Warning'}, 266: {'description': '<2A09>Port1-MSLD_FWD timeout', 'level': 'Warning'},
    267: {'description': '<2A0A>Port1-MPOS_Down timeout', 'level': 'Warning'}, 268: {'description': '<2A0B>Port1-MPOS_Up timeout', 'level': 'Warning'},
    269: {'description': '<2A0C>Port1-CLOC_Down timeout', 'level': 'Warning'}, 270: {'description': '<2A0D>Port1-CLOC_Up timeout', 'level': 'Warning'},
    271: {'description': '<2A0E>Port1-CSLD_BWD timeout', 'level': 'Warning'}, 272: {'description': '<2A0F>Port1-CSLD_FWD timeout', 'level': 'Warning'},
    273: {'description': '<2A50>Port1-MagDetectionsensorwarning', 'level': 'Warning'}, 274: {'description': '<2A51>Port1-Cart Detection Warning', 'level': 'Warning'},
    275: {'description': '<2A52>Port1-Magazine not exist warning', 'level': 'Warning'}, 276: {'description': '<2A53>Port1_SafetySensor warning', 'level': 'Warning'},
    281: {'description': '<2A58>Port1-RFID Communication Warning', 'level': 'Warning'}, 282: {'description': '<2A59>Port1-RFID read NG Warning', 'level': 'Warning'},
    289: {'description': '<30A0>Port2-Mag.Lift Inverter error', 'level': 'Error'}, 290: {'description': '<30A1>Port2-Shutter Inverter error', 'level': 'Error'},
    291: {'description': '<30A2>Port2-CSLD Inverter error', 'level': 'Error'}, 292: {'description': '<30A3>Port2-MSLD Driver error', 'level': 'Error'},
    293: {'description': '<30A4>Port2-MPOS Driver error', 'level': 'Error'}, 294: {'description': '<30A5>Port2-CLOC Driver error', 'level': 'Error'},
    295: {'description': '<30A6>Port2-Homing Impossible', 'level': 'Error'}, 297: {'description': '<30A8>Port2-MagLift Com. error', 'level': 'Error'},
    298: {'description': '<30A9>Port2-Shutter Com. error', 'level': 'Error'}, 299: {'description': '<30AA>Port2-CSLD Com. error', 'level': 'Error'},
    300: {'description': '<30AB>Port2-MSLD Com. error', 'level': 'Error'}, 301: {'description': '<30AC>Port2-MPOS Com. error', 'level': 'Error'},
    302: {'description': '<30AD>Port2-CLOC Com. error', 'level': 'Error'}, 305: {'description': '<30F0> Port2-CLOC Motion error', 'level': 'Error'},
    306: {'description': '<30F1> Port2-CLOC Memory Lost error', 'level': 'Error'}, 321: {'description': '<3500>Port2-Shutter open timeout', 'level': 'Alarm'},
    322: {'description': '<3501>Port2-Shutter close timeout', 'level': 'Alarm'}, 323: {'description': '<3502>Port2-Homing timeout', 'level': 'Alarm'},
    324: {'description': '<3503>Port2-Mag.Lift up timeout', 'level': 'Alarm'}, 325: {'description': '<3504>Port2-Mag.Lift down timeout', 'level': 'Alarm'},
    326: {'description': '<3505>Port2-Mappingtimeout', 'level': 'Alarm'}, 327: {'description': '<3506>Port2-MappingMismatch', 'level': 'Alarm'},
    328: {'description': '<3507>Port2-MSLD_BWD timeout', 'level': 'Alarm'}, 329: {'description': '<3508>Port2-MSLD_FWD timeout', 'level': 'Alarm'},
    330: {'description': '<3509>Port2-MPOS_Down timeout', 'level': 'Alarm'}, 331: {'description': '<350A>Port2-MPOS_Up timeout', 'level': 'Alarm'},
    332: {'description': '<350B>Port2-CLOC_Down timeout', 'level': 'Alarm'}, 333: {'description': '<350C>Port2-CLOC_Up timeout', 'level': 'Alarm'},
    334: {'description': '<350D>Port2-CSLD_BWD timeout', 'level': 'Alarm'}, 335: {'description': '<350E>Port2-CSLD_FWD timeout', 'level': 'Alarm'},
    345: {'description': '<3558>Port2-Shutter interlock', 'level': 'Alarm'}, 346: {'description': '<3559>Port2-Shutter interlock', 'level': 'Alarm'},
    347: {'description': '<355A>Port2-Panel positionAbnormally', 'level': 'Alarm'}, 348: {'description': '<355B>Port2-RFID read error [Read NG]', 'level': 'Alarm'},
    349: {'description': '<355C>Port2-MSLD interlock', 'level': 'Alarm'}, 350: {'description': '<355D>Port2-MPOS interlock', 'level': 'Alarm'},
    351: {'description': '<355E>Port2-CLOC interlock', 'level': 'Alarm'}, 352: {'description': '<355F>Port2-CSLD interlock', 'level': 'Alarm'},
    353: {'description': '<3A00>Port2-Shutter open warning', 'level': 'Warning'}, 354: {'description': '<3A01>Port2-Shutter close warning', 'level': 'Warning'},
    356: {'description': '<3A03>Port2-Mag.Lift up warning', 'level': 'Warning'}, 357: {'description': '<3A04>Port2-Mag.Lift down warning', 'level': 'Warning'},
    358: {'description': '<3A05>Port2-Mappingtimeout warning', 'level': 'Warning'}, 359: {'description': '<3A06>Port2-MappingMismatch warning', 'level': 'Warning'},
    360: {'description': '<3A07>Port2-SafetySensor_warning', 'level': 'Warning'}, 361: {'description': '<3A08>Port2-MSLD_BWD timeout', 'level': 'Warning'},
    362: {'description': '<3A09>Port2-MSLD_FWD timeout', 'level': 'Warning'}, 363: {'description': '<3A0A>Port2-MPOS_Down timeout', 'level': 'Warning'},
    364: {'description': '<3A0B>Port2-MPOS_Up timeout', 'level': 'Warning'}, 365: {'description': '<3A0C>Port2-CLOC_Down timeout', 'level': 'Warning'},
    366: {'description': '<3A0D>Port2-CLOC_Up timeout', 'level': 'Warning'}, 367: {'description': '<3A0E>Port2-CSLD_BWD timeout', 'level': 'Warning'},
    368: {'description': '<3A0F>Port2-CSLD_FWD timeout', 'level': 'Warning'}, 369: {'description': '<3A50>Port2-MagDetectionsensorwarning', 'level': 'Warning'},
    370: {'description': '<3A51>Port2-Cart Detection Warning', 'level': 'Warning'}, 371: {'description': '<3A52>Port2-Magazine not exist warning', 'level': 'Warning'},
    377: {'description': '<3A58>Port2-RFID Communication Warning', 'level': 'Warning'}, 378: {'description': '<3A59>Port2-RFID read NG Warning', 'level': 'Warning'},
    385: {'description': '<40A0>Port3-Mag.Lift Inverter error', 'level': 'Error'}, 386: {'description': '<40A1>Port3-Shutter Inverter error', 'level': 'Error'},
    387: {'description': '<40A2>Port3-CSLD Inverter error', 'level': 'Error'}, 388: {'description': '<40A3>Port3-MSLD Driver error', 'level': 'Error'},
    389: {'description': '<40A4>Port3-MPOS Driver error', 'level': 'Error'}, 390: {'description': '<40A5>Port3-CLOC Driver error', 'level': 'Error'},
    391: {'description': '<40A6>Port3-Homing Impossible', 'level': 'Error'}, 393: {'description': '<40A8>Port3-MagLift Com. error', 'level': 'Error'},
    394: {'description': '<40A9>Port3-Shutter Com. error', 'level': 'Error'}, 395: {'description': '<40AA>Port3-CSLD Com. error', 'level': 'Error'},
    396: {'description': '<40AB>Port3-MSLD Com. error', 'level': 'Error'}, 397: {'description': '<40AC>Port3-MPOS Com. error', 'level': 'Error'},
    398: {'description': '<40AD>Port3-CLOC Com. error', 'level': 'Error'}, 417: {'description': '<4500>Port3-Shutter open timeout', 'level': 'Alarm'},
    418: {'description': '<4501>Port3-Shutter close timeout', 'level': 'Alarm'}, 419: {'description': '<4502>Port3-Homing timeout', 'level': 'Alarm'},
    420: {'description': '<4503>Port3-Mag.Lift up timeout', 'level': 'Alarm'}, 421: {'description': '<4504>Port3-Mag.Lift down timeout', 'level': 'Alarm'},
    422: {'description': '<4505>Port3-Mappingtimeout', 'level': 'Alarm'}, 423: {'description': '<4506>Port3-MappingMismatch', 'level': 'Alarm'},
    424: {'description': '<4507>Port3-MSLD_BWD timeout', 'level': 'Alarm'}, 425: {'description': '<4508>Port3-MSLD_FWD timeout', 'level': 'Alarm'},
    426: {'description': '<4509>Port3-MPOS_Down timeout', 'level': 'Alarm'}, 427: {'description': '<450A>Port3-MPOS_Up timeout', 'level': 'Alarm'},
    428: {'description': '<450B>Port3-CLOC_Down timeout', 'level': 'Alarm'}, 429: {'description': '<450C>Port3-CLOC_Up timeout', 'level': 'Alarm'},
    430: {'description': '<4513>Port3-CSLD_BWD timeout', 'level': 'Alarm'}, 431: {'description': '<4514>Port3-CSLD_FWD timeout', 'level': 'Alarm'},
    433: {'description': '<7550> CV-Panel exist error', 'level': 'Alarm'}, 434: {'description': '<7551> CV-Separation error(UpperEQ)', 'level': 'Alarm'},
    435: {'description': '<7552> CV-Separation error(LowerEQ)', 'level': 'Alarm'}, 441: {'description': '<4558>Port3-Shutter interlock', 'level': 'Alarm'},
    442: {'description': '<4559>Port3-Mag.Lift interlock', 'level': 'Alarm'}, 443: {'description': '<455A>Port3-Panel positionAbnormally', 'level': 'Alarm'},
    444: {'description': '<455B>Port3-RFID read error [Read NG]', 'level': 'Alarm'}, 445: {'description': '<455C>Port3-MSLD interlock', 'level': 'Alarm'},
    446: {'description': '<455D>Port3-MPOS interlock', 'level': 'Alarm'}, 447: {'description': '<455E>Port3-CLOC interlock', 'level': 'Alarm'},
    448: {'description': '<455F>Port3-CSLD interlock', 'level': 'Alarm'}, 449: {'description': '<4A00>Port3-Shutter open warning', 'level': 'Warning'},
    450: {'description': '<4A01>Port3-Shutter close warning', 'level': 'Warning'}, 452: {'description': '<4A03>Port3-Mag.Lift up warnin', 'level': 'Warning'},
    453: {'description': '<4A04>Port3-Mag.Lift down warn', 'level': 'Warning'}, 454: {'description': '<4A05>Port3-Mappingtimeout warning', 'level': 'Warning'},
    455: {'description': '<4A06>Port3-MappingMismatch warning', 'level': 'Warning'}, 456: {'description': '<4A07>Port3-SafetySensor_warning', 'level': 'Warning'},
    457: {'description': '<4A08>Port3-MSLD_BWD timeout', 'level': 'Warning'}, 458: {'description': '<4A09>Port3-MSLD_FWD timeout', 'level': 'Warning'},
    459: {'description': '<4A0A>Port3-MPOS_Down timeout', 'level': 'Warning'}, 460: {'description': '<4A0B>Port3-MPOS_Up timeout', 'level': 'Warning'},
    461: {'description': '<4A0C>Port3-CLOC_Down timeout', 'level': 'Warning'}, 462: {'description': '<4A0D>Port3-CLOC_Up timeout', 'level': 'Warning'},
    463: {'description': '<4A0E>Port3-CSLD_BWD timeout', 'level': 'Warning'}, 464: {'description': '<4A0F>Port3-CSLD_FWD timeout', 'level': 'Warning'},
    465: {'description': '<4A50>Port3-Mag.Detect sensor warning', 'level': 'Warning'}, 466: {'description': '<4A51>Port3-Cart Detection warning', 'level': 'Warning'},
    467: {'description': '<4A52>Port3-Magazine not exist warning', 'level': 'Warning'}, 473: {'description': '<4A58>Port1-RFID Communication Warning', 'level': 'Warning'},
    481: {'description': '<8550> Process-Panel removed', 'level': 'Alarm'}, 482: {'description': '<8551> Process-Panel exist error', 'level': 'Alarm'},
    483: {'description': '<8552> Process-SMEMA signal error', 'level': 'Alarm'}, 513: {'description': '<0C80>LoadToToolcompleteEventTimeout', 'level': 'Alarm'},
    514: {'description': '<0C81>UnloadFromToolCompletedEventTime', 'level': 'Alarm'}, 515: {'description': '<0C82>MagToMag completedEventTimeout', 'level': 'Alarm'},
    516: {'description': '<0C83>MagCheck completedEventTimeout', 'level': 'Alarm'}, 517: {'description': '<0C84>LoadMag completedEventTimeout', 'level': 'Alarm'},
    518: {'description': '<0C85>CheckSlot completedEventTimeout', 'level': 'Alarm'}, 519: {'description': '<0C86>LoadToTool startedEventTimeout', 'level': 'Alarm'},
    520: {'description': '<0C87>UnloadFromTool startedEventTime', 'level': 'Alarm'}, 521: {'description': '<0C88>MagToMag startedEventTimeout', 'level': 'Alarm'},
    522: {'description': '<0C89>MagCheck startedEventTimeout', 'level': 'Alarm'}, 523: {'description': '<0C8A>LoadMag startedEventTimeout', 'level': 'Alarm'},
    524: {'description': '<0C8B>CheckSlot startedEventTimeout', 'level': 'Alarm'}, 525: {'description': '<0C8C>HC communication Timeout', 'level': 'Alarm'},
    526: {'description': '<0C8D>Can not execute remote command', 'level': 'Alarm'}, 529: {'description': '<0C90>ID readEventTimeout', 'level': 'Alarm'},
    530: {'description': '<0C91>UnloadedFromMagEventTimeout', 'level': 'Alarm'}, 531: {'description': '<0C92>LoadedToMagEventTimeout', 'level': 'Alarm'},
    532: {'description': '<0C93>UnloadedFromToolEventTimeout', 'level': 'Alarm'}, 533: {'description': '<0C94>LoadedToToolEventTimeout', 'level': 'Alarm'},
    534: {'description': '<0C95>UnloadedFromM.P.EventTimeout', 'level': 'Alarm'}, 535: {'description': '<0C96>LoadedToMPEventTimeout', 'level': 'Alarm'},
    538: {'description': '<0C99>UnloadedFromTool timeout', 'level': 'Alarm'}, 539: {'description': '<0C9A>LoadedToTool timeout', 'level': 'Alarm'},
    540: {'description': '<0C9B>PortCmdCanceled timeout', 'level': 'Alarm'}, 541: {'description': '<0C9C>QueueExecuteFail', 'level': 'Alarm'},
    542: {'description': '<0C9D>PortCmdRemoved timeout', 'level': 'Alarm'}, 543: {'description': '<0C9E>PP-Selected timeout', 'level': 'Alarm'},
    545: {'description': '<0D80>LoadToTool completedEventWarnig', 'level': 'Warning'}, 546: {'description': '<0D81>UnloadFromToolCompletedEventWar.', 'level': 'Warning'},
    547: {'description': '<0D82>MagToMag completedEventWarning', 'level': 'Warning'}, 548: {'description': '<0D83>MagCheck completedEventWarning', 'level': 'Warning'},
    549: {'description': '<0D84>LoadMag completedEventWarning', 'level': 'Warning'}, 550: {'description': '<0D85>CheckSlot completedEventWarning', 'level': 'Warning'},
    551: {'description': '<0D86>LoadToTool startedEventWarning', 'level': 'Warning'}, 552: {'description': '<0D87>UnloadFromTool startedEventWar.', 'level': 'Warning'},
    553: {'description': '<0D88>MagToMag startedEventWarning', 'level': 'Warning'}, 554: {'description': '<0D89>MagCheck startedEventWarning', 'level': 'Warning'},
    555: {'description': '<0D8A>LoadMag startedEventWarning', 'level': 'Warning'}, 556: {'description': '<0D8B>CheckSlot startedEventWarning', 'level': 'Warning'},
    557: {'description': '<0D8C>HC communication Warning', 'level': 'Warning'}, 561: {'description': '<0D90>ID readEventWarning', 'level': 'Warning'},
    562: {'description': '<0D91>UnloadedFromMagEventWarning', 'level': 'Warning'}, 563: {'description': '<0D92>LoadedToMagEventWarning', 'level': 'Warning'},
    564: {'description': '<0D93>UnloadedFromM.P.EventWarning', 'level': 'Warning'}, 565: {'description': '<0D94>UnloadedFromToolEventWarning', 'level': 'Warning'},
    566: {'description': '<0D95>LoadedToToolEventWarning', 'level': 'Warning'}, 567: {'description': '<0D96>LoadedToMPEventWarning', 'level': 'Warning'},
    568: {'description': '<0D97>ReplyMappingCheck Failed', 'level': 'Warning'}, 570: {'description': '<0D99>UnloadedFromTool Warning', 'level': 'Warning'},
    571: {'description': '<0D9A>LoadedToTool Warning', 'level': 'Warning'}, 609: {'description': '<1560>ID read error [Read NG]', 'level': 'Alarm'},
    610: {'description': '<1561>ID read error [Front/Back]', 'level': 'Alarm'}, 611: {'description': '<1562>ID read error [Unknown panel]', 'level': 'Alarm'},
    612: {'description': '<1563>ID read error [Duplicate ID]', 'level': 'Alarm'}, 613: {'description': '<1564>ID read error [Slot mismatch]', 'level': 'Alarm'},
    614: {'description': '<1565>ID read error [No notch]', 'level': 'Alarm'}, 615: {'description': '<1567>ID read error [Bad panel forMES]', 'level': 'Alarm'},
    616: {'description': '<1568>ID read error [Reply timeout ]', 'level': 'Alarm'}, 673: {'description': '<6050>OPCV1-Conveyor driver error', 'level': 'Error'},
    674: {'description': '<6051>OPCV1-Conveyor Com. error', 'level': 'Error'}, 689: {'description': '<7050>OPCV2-Conveyor driver error', 'level': 'Error'},
    690: {'description': '<7051>OPCV2-Conveyor Com. error', 'level': 'Error'}, 705: {'description': '<6550>OPCV1-Panel existAlarm', 'level': 'Alarm'},
    706: {'description': '<6551>OPCV1-SeparationAlarm Up-EQ', 'level': 'Alarm'}, 707: {'description': '<6552>OPCV1-SeparationAlarm Dn-EQ', 'level': 'Alarm'},
    715: {'description': '<655A>OPCV1-Motion timeover[Carry-in]', 'level': 'Alarm'}, 716: {'description': '<655B>OPCV1-Motion timeover[Carry-out]', 'level': 'Alarm'},
    719: {'description': '<655E>OPCV1-Motion time over [Home]', 'level': 'Alarm'}, 721: {'description': '<7550>OPCV2-Panel exist error', 'level': 'Alarm'},
    722: {'description': '<7551>OPCV2-Separation error Up-EQ', 'level': 'Alarm'}, 723: {'description': '<7552>OPCV2-SeparationAlarm Dn-EQ', 'level': 'Alarm'},
    731: {'description': '<755A>OPCV2-Motion timeover[Carry-in]', 'level': 'Alarm'}, 732: {'description': '<755B>OPCV2-Motion timeover[Carry-out]', 'level': 'Alarm'},
    735: {'description': '<755E>OPCV2-Motion time over [Home]', 'level': 'Alarm'}, 769: {'description': '<5050>PFL-Panel fall out', 'level': 'Error'},
    770: {'description': '<5051>PFL-Interference error', 'level': 'Error'}, 771: {'description': '<5052>PFL-Conveyor driver error', 'level': 'Error'},
    772: {'description': '<5053>PFL-Clamp Unit Inverter error', 'level': 'Error'}, 777: {'description': '<5058>PFL-Conveyor driver COM. error', 'level': 'Error'},
    778: {'description': '<5059>PFL-Clamp Inverter COM. error', 'level': 'Error'}, 801: {'description': '<5550>PFL-Panel exist error', 'level': 'Alarm'},
    802: {'description': '<5551>PFL-Separation error(UpperEQ)', 'level': 'Alarm'}, 803: {'description': '<5552>PFL-Separation error(LowerEQ)', 'level': 'Alarm'},
    807: {'description': '<5556>PFL-Clamp timeout', 'level': 'Alarm'}, 808: {'description': '<5557>PFL-Unclamp timeout', 'level': 'Alarm'},
    809: {'description': '<5558>PFL-Motion time over [Flip]', 'level': 'Alarm'}, 811: {'description': '<555A>PFL-Motion time over [Carry-in]', 'level': 'Alarm'},
    812: {'description': '<555B>PFL-Motion time over [Carry-out]', 'level': 'Alarm'}, 815: {'description': '<555E>PFL-Motion time over [Home]', 'level': 'Alarm'},
    865: {'description': '<80A0>STG1_CENT1_Driver error', 'level': 'Error'}, 866: {'description': '<80A1>STG1_Panel separation error', 'level': 'Error'},
    871: {'description': '<80A6>STG1-Homing Impossible', 'level': 'Error'}, 873: {'description': '<80A8>STG1_CENT1_Driver COM. error', 'level': 'Error'},
    881: {'description': '<90A0>STG2_CENT1_Driver error', 'level': 'Error'}, 882: {'description': '<90A1>STG2_Panel separation error', 'level': 'Error'},
    887: {'description': '<90A6>STG2-Homing Impossible', 'level': 'Error'}, 889: {'description': '<90A8>STG2_CENT1_Driver COM. error', 'level': 'Error'},
    897: {'description': '<8550>STG1_Panel exist error', 'level': 'Alarm'}, 898: {'description': '<8551>STG1_Timeover [Receive]', 'level': 'Alarm'},
}
